// Comprehensive seed data for Vaaney marketplace
// 10 Products with 5+ variants each
// 10 Services with 3 packages each
// Different workflow configurations

export interface ProductSeed {
  name: string;
  description: string;
  category: string;
  requiresQuote: boolean;
  requiresDesignApproval: boolean;
  images: string[]; // Stock image search terms
  variants: VariantSeed[];
}

export interface VariantSeed {
  name: string;
  sku: string;
  price: number;
  inventory: number;
  attributes: Record<string, string>;
  weight: number; // KG
  length: number; // CM
  width: number; // CM
  height: number; // CM
  imageSearch: string; // Stock image search term
}

export interface ServiceSeed {
  name: string;
  description: string;
  category: string;
  requiresQuote: boolean;
  requiresDesignApproval: boolean;
  images: string[]; // Stock image search terms
  packages: PackageSeed[];
}

export interface PackageSeed {
  name: string;
  description: string;
  price: number;
  features: string[];
  duration: number; // days
  availability: number;
}

export const PRODUCTS: ProductSeed[] = [
  // 1. Business Cards - Simple, direct purchase
  {
    name: "Premium Business Cards",
    description: "Professional business cards printed on high-quality card stock. Perfect for making a lasting impression. Available in multiple finishes and quantities. Fast turnaround time with delivery across Maldives.",
    category: "Business Stationery",
    requiresQuote: false,
    requiresDesignApproval: false,
    images: ["professional business cards"],
    variants: [
      {
        name: "Standard Matte - 100 cards",
        sku: "BC-STD-MAT-100",
        price: 25.00,
        inventory: 100,
        attributes: { finish: "Matte", quantity: "100", paper: "300gsm" },
        weight: 0.05,
        length: 9,
        width: 5.5,
        height: 0.5,
        imageSearch: "matte business cards stack",
      },
      {
        name: "Standard Glossy - 100 cards",
        sku: "BC-STD-GLO-100",
        price: 28.00,
        inventory: 100,
        attributes: { finish: "Glossy", quantity: "100", paper: "300gsm" },
        weight: 0.05,
        length: 9,
        width: 5.5,
        height: 0.5,
        imageSearch: "glossy business cards professional",
      },
      {
        name: "Premium Embossed - 100 cards",
        sku: "BC-PREM-EMB-100",
        price: 45.00,
        inventory: 50,
        attributes: { finish: "Embossed", quantity: "100", paper: "400gsm" },
        weight: 0.07,
        length: 9,
        width: 5.5,
        height: 0.6,
        imageSearch: "embossed business cards luxury",
      },
      {
        name: "Standard Matte - 250 cards",
        sku: "BC-STD-MAT-250",
        price: 55.00,
        inventory: 75,
        attributes: { finish: "Matte", quantity: "250", paper: "300gsm" },
        weight: 0.12,
        length: 9,
        width: 5.5,
        height: 1.2,
        imageSearch: "business cards bulk matte",
      },
      {
        name: "Premium Foil - 100 cards",
        sku: "BC-PREM-FOIL-100",
        price: 65.00,
        inventory: 40,
        attributes: { finish: "Gold Foil", quantity: "100", paper: "400gsm" },
        weight: 0.07,
        length: 9,
        width: 5.5,
        height: 0.6,
        imageSearch: "gold foil business cards elegant",
      },
      {
        name: "Premium Glossy - 250 cards",
        sku: "BC-PREM-GLO-250",
        price: 75.00,
        inventory: 60,
        attributes: { finish: "Glossy", quantity: "250", paper: "350gsm" },
        weight: 0.14,
        length: 9,
        width: 5.5,
        height: 1.3,
        imageSearch: "glossy business cards premium stack",
      },
    ],
  },

  // 2. A4 Flyers - Requires design approval
  {
    name: "A4 Promotional Flyers",
    description: "Eye-catching A4 flyers perfect for promotions, events, and marketing campaigns. Upload your design for approval before printing. High-quality printing with vibrant colors guaranteed.",
    category: "Marketing Materials",
    requiresQuote: false,
    requiresDesignApproval: true,
    images: ["promotional flyers colorful"],
    variants: [
      {
        name: "Standard Paper - 100 flyers",
        sku: "FLY-A4-STD-100",
        price: 35.00,
        inventory: 150,
        attributes: { size: "A4", paper: "100gsm", quantity: "100" },
        weight: 0.6,
        length: 29.7,
        width: 21,
        height: 0.5,
        imageSearch: "a4 flyers standard paper",
      },
      {
        name: "Glossy Paper - 100 flyers",
        sku: "FLY-A4-GLO-100",
        price: 45.00,
        inventory: 120,
        attributes: { size: "A4", paper: "130gsm Glossy", quantity: "100" },
        weight: 0.8,
        length: 29.7,
        width: 21,
        height: 0.6,
        imageSearch: "glossy a4 flyers vibrant",
      },
      {
        name: "Premium Matt - 250 flyers",
        sku: "FLY-A4-MAT-250",
        price: 85.00,
        inventory: 100,
        attributes: { size: "A4", paper: "150gsm Matt", quantity: "250" },
        weight: 1.8,
        length: 29.7,
        width: 21,
        height: 1.5,
        imageSearch: "matte a4 flyers professional",
      },
      {
        name: "Standard Paper - 500 flyers",
        sku: "FLY-A4-STD-500",
        price: 150.00,
        inventory: 80,
        attributes: { size: "A4", paper: "100gsm", quantity: "500" },
        weight: 3.0,
        length: 29.7,
        width: 21,
        height: 2.5,
        imageSearch: "bulk a4 flyers stack",
      },
      {
        name: "Premium Glossy - 500 flyers",
        sku: "FLY-A4-GLO-500",
        price: 200.00,
        inventory: 60,
        attributes: { size: "A4", paper: "150gsm Glossy", quantity: "500" },
        weight: 3.8,
        length: 29.7,
        width: 21,
        height: 3.0,
        imageSearch: "premium glossy flyers bulk",
      },
    ],
  },

  // 3. Custom Banners - Requires quote (custom sizes)
  {
    name: "Custom Vinyl Banners",
    description: "Large format vinyl banners for indoor and outdoor use. Request a quote with your custom dimensions and specifications. Perfect for events, storefronts, and advertising. Weather-resistant materials available.",
    category: "Large Format Printing",
    requiresQuote: true,
    requiresDesignApproval: false,
    images: ["vinyl banner outdoor"],
    variants: [
      {
        name: "Indoor Banner - 3ft x 6ft",
        sku: "BAN-IND-3X6",
        price: 85.00,
        inventory: 30,
        attributes: { type: "Indoor", size: "3ft x 6ft", material: "Standard Vinyl" },
        weight: 1.5,
        length: 183,
        width: 91,
        height: 5,
        imageSearch: "indoor vinyl banner 3x6",
      },
      {
        name: "Outdoor Banner - 4ft x 8ft",
        sku: "BAN-OUT-4X8",
        price: 150.00,
        inventory: 25,
        attributes: { type: "Outdoor", size: "4ft x 8ft", material: "Weather-resistant Vinyl" },
        weight: 3.2,
        length: 244,
        width: 122,
        height: 5,
        imageSearch: "outdoor vinyl banner weather resistant",
      },
      {
        name: "Premium Indoor - 5ft x 10ft",
        sku: "BAN-PREM-IND-5X10",
        price: 220.00,
        inventory: 20,
        attributes: { type: "Indoor", size: "5ft x 10ft", material: "Premium Vinyl" },
        weight: 4.5,
        length: 305,
        width: 152,
        height: 5,
        imageSearch: "large indoor banner premium",
      },
      {
        name: "Outdoor Heavy Duty - 6ft x 12ft",
        sku: "BAN-OUT-HD-6X12",
        price: 350.00,
        inventory: 15,
        attributes: { type: "Outdoor", size: "6ft x 12ft", material: "Heavy Duty Vinyl" },
        weight: 7.8,
        length: 366,
        width: 183,
        height: 6,
        imageSearch: "heavy duty outdoor banner",
      },
      {
        name: "Mesh Banner - 4ft x 8ft (Wind-resistant)",
        sku: "BAN-MESH-4X8",
        price: 180.00,
        inventory: 18,
        attributes: { type: "Outdoor", size: "4ft x 8ft", material: "Mesh Vinyl (Wind-resistant)" },
        weight: 2.8,
        length: 244,
        width: 122,
        height: 5,
        imageSearch: "mesh vinyl banner wind resistant",
      },
    ],
  },

  // 4. Vehicle Wraps - Requires both quote AND design approval
  {
    name: "Vehicle Wraps & Graphics",
    description: "Professional vehicle wrapping services for cars, vans, and boats. Requires quote for custom sizing and design approval before production. Transform your vehicle into a mobile advertisement with our premium vinyl wraps.",
    category: "Vehicle Graphics",
    requiresQuote: true,
    requiresDesignApproval: true,
    images: ["vehicle wrap car"],
    variants: [
      {
        name: "Partial Wrap - Small Car",
        sku: "VW-PART-SM",
        price: 450.00,
        inventory: 10,
        attributes: { coverage: "Partial (Doors + Hood)", vehicle: "Small Car", material: "Cast Vinyl" },
        weight: 5.0,
        length: 200,
        width: 150,
        height: 10,
        imageSearch: "partial car wrap small vehicle",
      },
      {
        name: "Full Wrap - Sedan",
        sku: "VW-FULL-SED",
        price: 950.00,
        inventory: 8,
        attributes: { coverage: "Full Wrap", vehicle: "Sedan", material: "Premium Cast Vinyl" },
        weight: 12.0,
        length: 500,
        width: 180,
        height: 15,
        imageSearch: "full car wrap sedan professional",
      },
      {
        name: "Full Wrap - SUV/Van",
        sku: "VW-FULL-SUV",
        price: 1350.00,
        inventory: 6,
        attributes: { coverage: "Full Wrap", vehicle: "SUV/Van", material: "Premium Cast Vinyl" },
        weight: 18.0,
        length: 600,
        width: 200,
        height: 20,
        imageSearch: "suv vehicle wrap full coverage",
      },
      {
        name: "Boat Graphics - Small",
        sku: "VW-BOAT-SM",
        price: 550.00,
        inventory: 5,
        attributes: { coverage: "Custom Graphics", vehicle: "Small Boat", material: "Marine Grade Vinyl" },
        weight: 8.0,
        length: 300,
        width: 100,
        height: 10,
        imageSearch: "boat vinyl graphics marine",
      },
      {
        name: "Commercial Van - Full Branding",
        sku: "VW-VAN-COMM",
        price: 1650.00,
        inventory: 4,
        attributes: { coverage: "Full Branding Package", vehicle: "Commercial Van", material: "Heavy Duty Cast Vinyl" },
        weight: 22.0,
        length: 700,
        width: 220,
        height: 25,
        imageSearch: "commercial van wrap branding",
      },
    ],
  },

  // 5. Brochures - Design approval required
  {
    name: "Professional Brochures",
    description: "High-quality tri-fold and bi-fold brochures for your business. Upload your design for approval before we print. Perfect for marketing materials, product catalogs, and information packets. Available in multiple paper finishes.",
    category: "Marketing Materials",
    requiresQuote: false,
    requiresDesignApproval: true,
    images: ["professional brochure tri-fold"],
    variants: [
      {
        name: "Tri-fold A4 - Glossy 100pcs",
        sku: "BRO-TRI-GLO-100",
        price: 95.00,
        inventory: 80,
        attributes: { fold: "Tri-fold", size: "A4", finish: "Glossy", quantity: "100" },
        weight: 1.2,
        length: 29.7,
        width: 21,
        height: 1.0,
        imageSearch: "tri-fold brochure glossy professional",
      },
      {
        name: "Bi-fold A4 - Matte 100pcs",
        sku: "BRO-BI-MAT-100",
        price: 85.00,
        inventory: 90,
        attributes: { fold: "Bi-fold", size: "A4", finish: "Matte", quantity: "100" },
        weight: 1.0,
        length: 29.7,
        width: 21,
        height: 0.8,
        imageSearch: "bi-fold brochure matte elegant",
      },
      {
        name: "Tri-fold A4 - Premium 250pcs",
        sku: "BRO-TRI-PREM-250",
        price: 220.00,
        inventory: 60,
        attributes: { fold: "Tri-fold", size: "A4", finish: "Premium Matt Laminated", quantity: "250" },
        weight: 3.5,
        length: 29.7,
        width: 21,
        height: 2.5,
        imageSearch: "premium brochure laminated stack",
      },
      {
        name: "Square Fold - Glossy 100pcs",
        sku: "BRO-SQ-GLO-100",
        price: 105.00,
        inventory: 70,
        attributes: { fold: "Square Fold", size: "21cm x 21cm", finish: "Glossy", quantity: "100" },
        weight: 1.4,
        length: 21,
        width: 21,
        height: 1.0,
        imageSearch: "square fold brochure modern",
      },
      {
        name: "Tri-fold A4 - Silk 500pcs",
        sku: "BRO-TRI-SILK-500",
        price: 380.00,
        inventory: 40,
        attributes: { fold: "Tri-fold", size: "A4", finish: "Silk", quantity: "500" },
        weight: 6.0,
        length: 29.7,
        width: 21,
        height: 4.5,
        imageSearch: "silk finish brochure bulk",
      },
    ],
  },

  // 6. Posters - Simple with variants
  {
    name: "Promotional Posters",
    description: "High-quality posters in various sizes for advertising, events, and decoration. Printed on premium paper with vibrant colors. Available in multiple sizes from A3 to A0. Quick turnaround and delivery across Maldives.",
    category: "Marketing Materials",
    requiresQuote: false,
    requiresDesignApproval: false,
    images: ["promotional poster colorful"],
    variants: [
      {
        name: "A3 Poster - Glossy",
        sku: "POST-A3-GLO",
        price: 12.00,
        inventory: 200,
        attributes: { size: "A3 (29.7cm x 42cm)", finish: "Glossy", paper: "170gsm" },
        weight: 0.15,
        length: 42,
        width: 29.7,
        height: 0.1,
        imageSearch: "a3 poster glossy print",
      },
      {
        name: "A2 Poster - Matte",
        sku: "POST-A2-MAT",
        price: 18.00,
        inventory: 150,
        attributes: { size: "A2 (42cm x 59.4cm)", finish: "Matte", paper: "200gsm" },
        weight: 0.35,
        length: 59.4,
        width: 42,
        height: 0.1,
        imageSearch: "a2 poster matte professional",
      },
      {
        name: "A1 Poster - Premium Glossy",
        sku: "POST-A1-PREM",
        price: 28.00,
        inventory: 120,
        attributes: { size: "A1 (59.4cm x 84.1cm)", finish: "Premium Glossy", paper: "250gsm" },
        weight: 0.65,
        length: 84.1,
        width: 59.4,
        height: 0.15,
        imageSearch: "a1 poster large glossy",
      },
      {
        name: "A0 Poster - Matte",
        sku: "POST-A0-MAT",
        price: 45.00,
        inventory: 80,
        attributes: { size: "A0 (84.1cm x 118.9cm)", finish: "Matte", paper: "200gsm" },
        weight: 1.2,
        length: 118.9,
        width: 84.1,
        height: 0.2,
        imageSearch: "a0 poster extra large",
      },
      {
        name: "Custom Size - Premium",
        sku: "POST-CUST-PREM",
        price: 55.00,
        inventory: 60,
        attributes: { size: "Custom (up to 100cm x 150cm)", finish: "Your Choice", paper: "Premium Stock" },
        weight: 1.5,
        length: 150,
        width: 100,
        height: 0.2,
        imageSearch: "custom size poster premium",
      },
      {
        name: "A3 Poster Set - 10pcs Matte",
        sku: "POST-A3-SET10",
        price: 95.00,
        inventory: 100,
        attributes: { size: "A3 (29.7cm x 42cm)", finish: "Matte", paper: "170gsm", quantity: "10" },
        weight: 1.5,
        length: 42,
        width: 29.7,
        height: 1.0,
        imageSearch: "poster set multiple prints",
      },
    ],
  },

  // 7. Menu Cards - Design approval required
  {
    name: "Restaurant Menu Cards",
    description: "Professional menu cards for restaurants, cafes, and food businesses. Upload your menu design for approval. Available in multiple sizes and lamination options for durability. Perfect for dine-in and takeaway menus.",
    category: "Hospitality",
    requiresQuote: false,
    requiresDesignApproval: true,
    images: ["restaurant menu card elegant"],
    variants: [
      {
        name: "Single Page A4 - Laminated (10pcs)",
        sku: "MENU-SP-A4-LAM-10",
        price: 45.00,
        inventory: 100,
        attributes: { pages: "Single", size: "A4", finish: "Laminated", quantity: "10" },
        weight: 0.8,
        length: 29.7,
        width: 21,
        height: 0.5,
        imageSearch: "laminated menu single page",
      },
      {
        name: "Bi-fold A3 - Premium (10pcs)",
        sku: "MENU-BI-A3-PREM-10",
        price: 75.00,
        inventory: 80,
        attributes: { pages: "Bi-fold", size: "A3", finish: "Premium Glossy Laminated", quantity: "10" },
        weight: 1.5,
        length: 42,
        width: 29.7,
        height: 0.8,
        imageSearch: "bi-fold menu card restaurant",
      },
      {
        name: "Tri-fold A4 - Standard (20pcs)",
        sku: "MENU-TRI-A4-STD-20",
        price: 95.00,
        inventory: 90,
        attributes: { pages: "Tri-fold", size: "A4", finish: "Standard Laminated", quantity: "20" },
        weight: 2.0,
        length: 29.7,
        width: 21,
        height: 1.5,
        imageSearch: "tri-fold takeaway menu",
      },
      {
        name: "Booklet Style - 4 pages (10pcs)",
        sku: "MENU-BOOK-4PG-10",
        price: 120.00,
        inventory: 60,
        attributes: { pages: "4-page Booklet", size: "A4", finish: "Wire-bound Laminated", quantity: "10" },
        weight: 2.5,
        length: 29.7,
        width: 21,
        height: 2.0,
        imageSearch: "menu booklet wire bound",
      },
      {
        name: "Table Tent - Double Sided (10pcs)",
        sku: "MENU-TENT-DS-10",
        price: 55.00,
        inventory: 120,
        attributes: { type: "Table Tent", size: "A5", finish: "Sturdy Card Stock", quantity: "10" },
        weight: 0.6,
        length: 21,
        width: 14.8,
        height: 0.4,
        imageSearch: "table tent menu double sided",
      },
    ],
  },

  // 8. Stickers/Decals - Simple with variants
  {
    name: "Custom Stickers & Decals",
    description: "High-quality vinyl stickers and decals for branding, decoration, and labeling. Available in various shapes, sizes, and finishes. Weather-resistant options for outdoor use. Perfect for product labels, laptop stickers, and promotional giveaways.",
    category: "Promotional Items",
    requiresQuote: false,
    requiresDesignApproval: false,
    images: ["custom vinyl stickers"],
    variants: [
      {
        name: "Round Stickers - 5cm (100pcs)",
        sku: "STICK-RND-5CM-100",
        price: 35.00,
        inventory: 200,
        attributes: { shape: "Round", size: "5cm diameter", finish: "Glossy Vinyl", quantity: "100" },
        weight: 0.2,
        length: 10,
        width: 10,
        height: 1,
        imageSearch: "round vinyl stickers glossy",
      },
      {
        name: "Square Stickers - 7cm (100pcs)",
        sku: "STICK-SQ-7CM-100",
        price: 42.00,
        inventory: 180,
        attributes: { shape: "Square", size: "7cm x 7cm", finish: "Matte Vinyl", quantity: "100" },
        weight: 0.25,
        length: 10,
        width: 10,
        height: 1.2,
        imageSearch: "square stickers matte finish",
      },
      {
        name: "Die-Cut Custom Shape (50pcs)",
        sku: "STICK-DIE-CUST-50",
        price: 65.00,
        inventory: 100,
        attributes: { shape: "Custom Die-Cut", size: "up to 10cm", finish: "Premium Vinyl", quantity: "50" },
        weight: 0.15,
        length: 12,
        width: 12,
        height: 0.8,
        imageSearch: "die cut stickers custom shape",
      },
      {
        name: "Large Decal - 20cm (10pcs)",
        sku: "STICK-LRG-20CM-10",
        price: 45.00,
        inventory: 90,
        attributes: { shape: "Custom", size: "up to 20cm", finish: "Weather-resistant Vinyl", quantity: "10" },
        weight: 0.3,
        length: 25,
        width: 25,
        height: 0.5,
        imageSearch: "large vinyl decal outdoor",
      },
      {
        name: "Holographic Stickers - 5cm (100pcs)",
        sku: "STICK-HOLO-5CM-100",
        price: 55.00,
        inventory: 120,
        attributes: { shape: "Round/Square", size: "5cm", finish: "Holographic Vinyl", quantity: "100" },
        weight: 0.2,
        length: 10,
        width: 10,
        height: 1,
        imageSearch: "holographic stickers shiny",
      },
      {
        name: "Transparent Clear - 8cm (50pcs)",
        sku: "STICK-CLR-8CM-50",
        price: 48.00,
        inventory: 150,
        attributes: { shape: "Custom", size: "up to 8cm", finish: "Clear Transparent Vinyl", quantity: "50" },
        weight: 0.12,
        length: 10,
        width: 10,
        height: 0.6,
        imageSearch: "clear transparent stickers",
      },
    ],
  },

  // 9. Custom Packaging - Requires quote
  {
    name: "Custom Product Packaging",
    description: "Professional custom packaging solutions for your products. Request a quote with your specifications including box size, material, and printing requirements. Perfect for retail products, gift boxes, and e-commerce packaging.",
    category: "Packaging",
    requiresQuote: true,
    requiresDesignApproval: false,
    images: ["custom product packaging box"],
    variants: [
      {
        name: "Small Box - Standard (50pcs)",
        sku: "PKG-SM-STD-50",
        price: 125.00,
        inventory: 60,
        attributes: { size: "15cm x 10cm x 5cm", material: "E-flute Cardboard", printing: "Full Color", quantity: "50" },
        weight: 5.0,
        length: 50,
        width: 40,
        height: 20,
        imageSearch: "small product box packaging",
      },
      {
        name: "Medium Box - Premium (50pcs)",
        sku: "PKG-MD-PREM-50",
        price: 185.00,
        inventory: 50,
        attributes: { size: "25cm x 20cm x 10cm", material: "Premium B-flute", printing: "Full Color + UV Coating", quantity: "50" },
        weight: 12.0,
        length: 70,
        width: 60,
        height: 30,
        imageSearch: "medium gift box premium",
      },
      {
        name: "Large Shipping Box (25pcs)",
        sku: "PKG-LG-SHIP-25",
        price: 145.00,
        inventory: 40,
        attributes: { size: "40cm x 30cm x 20cm", material: "Heavy Duty Corrugated", printing: "2 Color", quantity: "25" },
        weight: 15.0,
        length: 90,
        width: 70,
        height: 40,
        imageSearch: "shipping box corrugated custom",
      },
      {
        name: "Luxury Gift Box - Small (20pcs)",
        sku: "PKG-LUX-SM-20",
        price: 165.00,
        inventory: 35,
        attributes: { size: "20cm x 15cm x 8cm", material: "Rigid Board with Magnetic Closure", printing: "Full Color + Foil", quantity: "20" },
        weight: 8.0,
        length: 50,
        width: 40,
        height: 25,
        imageSearch: "luxury gift box magnetic",
      },
      {
        name: "Pillow Box - Medium (100pcs)",
        sku: "PKG-PIL-MD-100",
        price: 95.00,
        inventory: 70,
        attributes: { size: "12cm x 10cm", material: "Card Stock", printing: "Full Color", quantity: "100" },
        weight: 3.5,
        length: 40,
        width: 30,
        height: 15,
        imageSearch: "pillow box packaging",
      },
    ],
  },

  // 10. Signage Boards - Requires both quote AND design approval
  {
    name: "Commercial Signage Boards",
    description: "Professional signage solutions for businesses and events. Requires quote for custom specifications and design approval before fabrication. Available in various materials including acrylic, aluminum composite, and LED-illuminated options.",
    category: "Signage",
    requiresQuote: true,
    requiresDesignApproval: true,
    images: ["commercial signage board"],
    variants: [
      {
        name: "Acrylic Board - 60cm x 40cm",
        sku: "SIGN-ACR-6040",
        price: 180.00,
        inventory: 25,
        attributes: { material: "3mm Acrylic", size: "60cm x 40cm", mounting: "Wall Mount", lighting: "No" },
        weight: 2.5,
        length: 60,
        width: 40,
        height: 0.3,
        imageSearch: "acrylic signage board modern",
      },
      {
        name: "Aluminum Composite - 90cm x 60cm",
        sku: "SIGN-ALU-9060",
        price: 285.00,
        inventory: 20,
        attributes: { material: "Aluminum Composite Panel", size: "90cm x 60cm", mounting: "Standoff", lighting: "No" },
        weight: 4.5,
        length: 90,
        width: 60,
        height: 0.5,
        imageSearch: "aluminum composite sign professional",
      },
      {
        name: "LED Backlit - 100cm x 50cm",
        sku: "SIGN-LED-10050",
        price: 550.00,
        inventory: 12,
        attributes: { material: "Acrylic with LED", size: "100cm x 50cm", mounting: "Wall Mount", lighting: "LED Backlit" },
        weight: 8.0,
        length: 100,
        width: 50,
        height: 5,
        imageSearch: "led backlit sign illuminated",
      },
      {
        name: "3D Letter Sign - Custom",
        sku: "SIGN-3D-CUST",
        price: 450.00,
        inventory: 10,
        attributes: { material: "Acrylic/PVC 3D Letters", size: "Custom (up to 50cm height)", mounting: "Wall Mount", lighting: "Optional" },
        weight: 6.0,
        length: 80,
        width: 50,
        height: 15,
        imageSearch: "3d letter sign dimensional",
      },
      {
        name: "Neon LED Sign - 80cm x 40cm",
        sku: "SIGN-NEON-8040",
        price: 680.00,
        inventory: 8,
        attributes: { material: "LED Neon Flex", size: "80cm x 40cm", mounting: "Wall/Window", lighting: "Multi-color LED" },
        weight: 5.5,
        length: 80,
        width: 40,
        height: 3,
        imageSearch: "neon led sign custom colorful",
      },
    ],
  },
];

export const SERVICES: ServiceSeed[] = [
  // 1. Logo Design - Simple booking
  {
    name: "Professional Logo Design",
    description: "Get a unique, professional logo for your business. Our expert designers will create multiple concepts for you to choose from. Includes unlimited revisions until you're 100% satisfied. Perfect for startups and rebrands.",
    category: "Graphic Design",
    requiresQuote: false,
    requiresDesignApproval: false,
    images: ["professional logo design modern"],
    packages: [
      {
        name: "Basic",
        description: "Perfect for startups and small businesses",
        price: 150.00,
        features: [
          "3 initial logo concepts",
          "2 rounds of revisions",
          "Final files in PNG and JPG",
          "Basic brand colors",
          "3-day delivery",
        ],
        duration: 3,
        availability: 20,
      },
      {
        name: "Standard",
        description: "Most popular choice for growing businesses",
        price: 300.00,
        features: [
          "5 initial logo concepts",
          "Unlimited revisions",
          "All file formats (AI, EPS, PNG, JPG, SVG)",
          "Complete brand color palette",
          "Social media kit",
          "5-day delivery",
        ],
        duration: 5,
        availability: 15,
      },
      {
        name: "Premium",
        description: "Complete branding solution for established businesses",
        price: 550.00,
        features: [
          "8 initial logo concepts",
          "Unlimited revisions",
          "All source files included",
          "Complete brand guidelines document",
          "Social media kit + templates",
          "Business card design",
          "Letterhead design",
          "7-day delivery with priority support",
        ],
        duration: 7,
        availability: 10,
      },
    ],
  },

  // 2. Social Media Graphics - Requires design approval
  {
    name: "Social Media Graphics Design",
    description: "Eye-catching social media graphics for your brand. Upload your content/images for approval, and we'll create stunning visuals optimized for all platforms. Includes Instagram, Facebook, LinkedIn, and Twitter formats.",
    category: "Social Media",
    requiresQuote: false,
    requiresDesignApproval: true,
    images: ["social media graphics colorful"],
    packages: [
      {
        name: "Basic",
        description: "Essential social media graphics package",
        price: 80.00,
        features: [
          "5 custom graphics",
          "Instagram + Facebook formats",
          "1 round of revisions",
          "Stock photos included",
          "2-day delivery",
        ],
        duration: 2,
        availability: 30,
      },
      {
        name: "Standard",
        description: "Complete monthly social media package",
        price: 200.00,
        features: [
          "15 custom graphics",
          "All major platforms (IG, FB, LinkedIn, Twitter)",
          "2 rounds of revisions",
          "Custom branded templates",
          "Stock photos + icons",
          "5-day delivery",
        ],
        duration: 5,
        availability: 20,
      },
      {
        name: "Premium",
        description: "Full-service social media design solution",
        price: 450.00,
        features: [
          "30 custom graphics",
          "All platforms including Stories & Reels",
          "Unlimited revisions",
          "Animated graphics (GIFs)",
          "Content calendar design",
          "Branded templates library",
          "7-day delivery with priority support",
        ],
        duration: 7,
        availability: 12,
      },
    ],
  },

  // 3. Custom Illustrations - Requires quote
  {
    name: "Custom Digital Illustrations",
    description: "Unique custom illustrations for your brand, book, or project. Request a quote with your specific requirements. Our talented illustrators work in various styles from minimalist to detailed realistic artwork.",
    category: "Illustration",
    requiresQuote: true,
    requiresDesignApproval: false,
    images: ["custom digital illustration art"],
    packages: [
      {
        name: "Basic",
        description: "Simple illustration for basic projects",
        price: 120.00,
        features: [
          "1 custom illustration",
          "Simple style (minimalist/flat)",
          "Basic color palette",
          "2 rounds of revisions",
          "PNG and JPG formats",
          "4-day delivery",
        ],
        duration: 4,
        availability: 15,
      },
      {
        name: "Standard",
        description: "Detailed illustration for professional use",
        price: 280.00,
        features: [
          "3 custom illustrations",
          "Medium complexity style",
          "Full color with details",
          "3 rounds of revisions",
          "All formats including vector (AI, SVG)",
          "Character design options",
          "7-day delivery",
        ],
        duration: 7,
        availability: 10,
      },
      {
        name: "Premium",
        description: "Complex illustration series for books/brands",
        price: 650.00,
        features: [
          "5+ custom illustrations",
          "Highly detailed/realistic style",
          "Complex scenes with backgrounds",
          "Unlimited revisions",
          "Complete source files",
          "Character design + variations",
          "Commercial usage rights",
          "14-day delivery with consultations",
        ],
        duration: 14,
        availability: 6,
      },
    ],
  },

  // 4. Brand Identity Package - Requires both quote AND design approval
  {
    name: "Complete Brand Identity Package",
    description: "Comprehensive brand identity solution including logo, colors, typography, and brand guidelines. Requires quote for custom scope and design approval at each milestone. Perfect for new businesses and complete rebrands.",
    category: "Branding",
    requiresQuote: true,
    requiresDesignApproval: true,
    images: ["brand identity package professional"],
    packages: [
      {
        name: "Basic",
        description: "Essential brand identity starter package",
        price: 450.00,
        features: [
          "Logo design (3 concepts)",
          "Color palette (3-5 colors)",
          "Typography selection",
          "Basic brand guidelines (PDF)",
          "Business card design",
          "Social media profile images",
          "10-day delivery",
        ],
        duration: 10,
        availability: 8,
      },
      {
        name: "Standard",
        description: "Professional brand identity system",
        price: 950.00,
        features: [
          "Logo design (5 concepts + variations)",
          "Complete color system",
          "Typography system (3 fonts)",
          "Comprehensive brand guidelines",
          "Stationery suite (cards, letterhead, envelope)",
          "Social media templates",
          "Email signature design",
          "Brand pattern/texture design",
          "14-day delivery with consultations",
        ],
        duration: 14,
        availability: 6,
      },
      {
        name: "Premium",
        description: "Enterprise-level complete brand system",
        price: 2200.00,
        features: [
          "Complete logo suite (8+ variations)",
          "Extended color palette with gradients",
          "Complete typography system",
          "100+ page brand guidelines book",
          "Full stationery suite",
          "Marketing collateral templates",
          "Website style guide",
          "Brand photography direction",
          "Iconography system",
          "Brand voice & messaging guide",
          "21-day delivery with weekly consultations",
        ],
        duration: 21,
        availability: 4,
      },
    ],
  },

  // 5. Web Development - Simple booking
  {
    name: "Professional Web Development",
    description: "Modern, responsive websites built with latest technologies. From simple landing pages to complex web applications. Mobile-friendly, fast-loading, and SEO-optimized. Perfect for businesses looking to establish their online presence.",
    category: "Web Development",
    requiresQuote: false,
    requiresDesignApproval: false,
    images: ["modern website development"],
    packages: [
      {
        name: "Basic",
        description: "Simple landing page or portfolio site",
        price: 500.00,
        features: [
          "1-3 page website",
          "Responsive mobile design",
          "Contact form integration",
          "Basic SEO setup",
          "1 month free support",
          "7-day delivery",
        ],
        duration: 7,
        availability: 12,
      },
      {
        name: "Standard",
        description: "Professional business website",
        price: 1200.00,
        features: [
          "5-10 page website",
          "Custom responsive design",
          "Content management system (CMS)",
          "Contact forms + email integration",
          "Advanced SEO optimization",
          "Google Analytics setup",
          "Social media integration",
          "3 months free support",
          "14-day delivery",
        ],
        duration: 14,
        availability: 8,
      },
      {
        name: "Premium",
        description: "Custom web application or e-commerce site",
        price: 3500.00,
        features: [
          "Unlimited pages",
          "Custom functionality & features",
          "E-commerce integration (if needed)",
          "User authentication system",
          "Database integration",
          "Admin dashboard",
          "API integrations",
          "Advanced security features",
          "Performance optimization",
          "6 months free support + training",
          "30-day delivery",
        ],
        duration: 30,
        availability: 4,
      },
    ],
  },

  // 6. Video Editing - Requires design approval (client provides footage)
  {
    name: "Professional Video Editing",
    description: "High-quality video editing for your content. Upload your raw footage for approval, and we'll create polished, engaging videos. Perfect for social media, YouTube, promotional content, and events. Includes color grading and motion graphics.",
    category: "Video Production",
    requiresQuote: false,
    requiresDesignApproval: true,
    images: ["professional video editing"],
    packages: [
      {
        name: "Basic",
        description: "Simple video editing for social media",
        price: 100.00,
        features: [
          "Up to 2 minutes final video",
          "Basic cuts and transitions",
          "Background music",
          "Simple text overlays",
          "1080p export",
          "1 round of revisions",
          "3-day delivery",
        ],
        duration: 3,
        availability: 20,
      },
      {
        name: "Standard",
        description: "Professional video editing for marketing",
        price: 280.00,
        features: [
          "Up to 5 minutes final video",
          "Advanced editing with effects",
          "Color grading & correction",
          "Motion graphics & animations",
          "Licensed music or custom soundtrack",
          "Professional text animations",
          "4K export available",
          "2 rounds of revisions",
          "5-day delivery",
        ],
        duration: 5,
        availability: 12,
      },
      {
        name: "Premium",
        description: "Full-service video production editing",
        price: 650.00,
        features: [
          "Up to 10 minutes final video",
          "Cinematic editing style",
          "Professional color grading",
          "Custom motion graphics package",
          "Sound design & mixing",
          "Multiple format exports",
          "YouTube/social media optimization",
          "Thumbnail design included",
          "Unlimited revisions",
          "7-day delivery with consultations",
        ],
        duration: 7,
        availability: 8,
      },
    ],
  },

  // 7. 3D Rendering - Requires quote
  {
    name: "Architectural 3D Rendering",
    description: "Photorealistic 3D renderings for architecture, interior design, and product visualization. Request a quote with your project specifications. Perfect for presenting designs to clients before construction or manufacturing.",
    category: "3D Design",
    requiresQuote: true,
    requiresDesignApproval: false,
    images: ["3d architectural rendering"],
    packages: [
      {
        name: "Basic",
        description: "Simple 3D rendering for basic projects",
        price: 250.00,
        features: [
          "1 3D rendering (exterior or interior)",
          "Basic lighting and materials",
          "Standard camera angle",
          "4K resolution",
          "1 round of revisions",
          "5-day delivery",
        ],
        duration: 5,
        availability: 10,
      },
      {
        name: "Standard",
        description: "Professional 3D rendering package",
        price: 550.00,
        features: [
          "3 3D renderings (multiple angles)",
          "Realistic lighting & shadows",
          "High-quality materials & textures",
          "Multiple camera angles",
          "Landscape/environment inclusion",
          "6K resolution",
          "2 rounds of revisions",
          "7-day delivery",
        ],
        duration: 7,
        availability: 6,
      },
      {
        name: "Premium",
        description: "Complete 3D visualization solution",
        price: 1400.00,
        features: [
          "5+ photorealistic renderings",
          "360° panoramic views",
          "Day/night lighting scenarios",
          "Premium materials library",
          "Detailed landscaping",
          "People & vehicle additions",
          "Animated walkthrough (30 sec)",
          "8K resolution",
          "Unlimited revisions",
          "14-day delivery with consultations",
        ],
        duration: 14,
        availability: 4,
      },
    ],
  },

  // 8. Mobile App UI/UX - Requires both quote AND design approval
  {
    name: "Mobile App UI/UX Design",
    description: "Modern, intuitive mobile app design for iOS and Android. Requires quote for custom scope and design approval at each design phase. Includes wireframes, mockups, and interactive prototypes. Perfect for startups and established businesses.",
    category: "App Design",
    requiresQuote: true,
    requiresDesignApproval: true,
    images: ["mobile app design modern"],
    packages: [
      {
        name: "Basic",
        description: "Essential app design for MVPs",
        price: 650.00,
        features: [
          "5-8 key screens designed",
          "Basic wireframes",
          "Simple UI design",
          "Basic color scheme",
          "1 device size (mobile only)",
          "2 rounds of revisions",
          "Static mockups (PNG)",
          "10-day delivery",
        ],
        duration: 10,
        availability: 8,
      },
      {
        name: "Standard",
        description: "Professional app design package",
        price: 1350.00,
        features: [
          "15-20 screens designed",
          "Detailed wireframes & user flows",
          "Complete UI design system",
          "Custom icon set",
          "Design for iOS & Android",
          "Interactive prototype (Figma)",
          "Design handoff files",
          "3 rounds of revisions",
          "14-day delivery with consultations",
        ],
        duration: 14,
        availability: 6,
      },
      {
        name: "Premium",
        description: "Complete app design solution",
        price: 3200.00,
        features: [
          "30+ screens designed",
          "Complete UX research & strategy",
          "User journey mapping",
          "Full design system with components",
          "Custom illustrations & animations",
          "iOS, Android, & Tablet designs",
          "Fully interactive prototype",
          "Developer handoff package",
          "Micro-interactions design",
          "Usability testing included",
          "Unlimited revisions",
          "21-day delivery with weekly reviews",
        ],
        duration: 21,
        availability: 3,
      },
    ],
  },

  // 9. Content Writing - Simple booking
  {
    name: "Professional Content Writing",
    description: "SEO-optimized content writing for websites, blogs, and marketing materials. Our experienced writers create engaging, well-researched content that drives traffic and conversions. Perfect for businesses needing regular content production.",
    category: "Content Creation",
    requiresQuote: false,
    requiresDesignApproval: false,
    images: ["professional content writing"],
    packages: [
      {
        name: "Basic",
        description: "Essential content for small businesses",
        price: 80.00,
        features: [
          "Up to 1000 words",
          "1 blog post or article",
          "Basic SEO optimization",
          "1 round of revisions",
          "Plagiarism check included",
          "3-day delivery",
        ],
        duration: 3,
        availability: 25,
      },
      {
        name: "Standard",
        description: "Professional content package",
        price: 250.00,
        features: [
          "Up to 3000 words",
          "3-4 blog posts or 1 long-form article",
          "Advanced SEO optimization",
          "Keyword research included",
          "Meta descriptions",
          "2 rounds of revisions",
          "Plagiarism check",
          "7-day delivery",
        ],
        duration: 7,
        availability: 15,
      },
      {
        name: "Premium",
        description: "Complete content marketing solution",
        price: 650.00,
        features: [
          "Up to 8000 words",
          "8-10 blog posts or mixed content",
          "Comprehensive SEO strategy",
          "Keyword research & competitor analysis",
          "Meta tags & descriptions",
          "Internal linking strategy",
          "Content calendar planning",
          "Social media snippets",
          "Unlimited revisions",
          "14-day delivery with consultations",
        ],
        duration: 14,
        availability: 10,
      },
    ],
  },

  // 10. Photo Retouching - Design approval required (upload photos)
  {
    name: "Professional Photo Retouching",
    description: "High-end photo retouching and enhancement services. Upload your photos for approval, and we'll deliver professionally edited images. Perfect for portraits, product photos, real estate, and events. Natural-looking results guaranteed.",
    category: "Photography",
    requiresQuote: false,
    requiresDesignApproval: true,
    images: ["professional photo retouching"],
    packages: [
      {
        name: "Basic",
        description: "Simple photo editing and enhancement",
        price: 45.00,
        features: [
          "Up to 5 photos",
          "Basic color correction",
          "Brightness/contrast adjustment",
          "Crop and straighten",
          "Minor blemish removal",
          "1 round of revisions",
          "2-day delivery",
        ],
        duration: 2,
        availability: 30,
      },
      {
        name: "Standard",
        description: "Professional retouching package",
        price: 120.00,
        features: [
          "Up to 15 photos",
          "Advanced color grading",
          "Skin retouching & smoothing",
          "Background cleanup",
          "Object removal",
          "Lighting enhancement",
          "2 rounds of revisions",
          "4-day delivery",
        ],
        duration: 4,
        availability: 20,
      },
      {
        name: "Premium",
        description: "Complete photo editing solution",
        price: 300.00,
        features: [
          "Up to 30 photos",
          "Professional beauty retouching",
          "Background replacement",
          "Advanced compositing",
          "HDR processing",
          "Frequency separation technique",
          "Dodge and burn",
          "Perfect skin tones",
          "Unlimited revisions",
          "6-day delivery with consultations",
        ],
        duration: 6,
        availability: 12,
      },
    ],
  },
];
